### ISSUE TITLE
nondeterministic results for same input

### ISSUE THREAD

**Issue by jsmedmar** [cancerit/vafCorrect#45] opened 2018-06-04 15:57 UTC
Best regards, 

We are getting non deterministic output for same input after running multiple times. We are trying to vafcorrect some indels on a targeted bam and we get different vaf values every time. Interestingly, the output varies between states. Say for one run vafs reported were `0.04, 0.00, 0.00, 1.00` and for the other run vafs were`0.05, 0.00, 0.07, 0.00`. Then, every time `cgpVaf.pl` is run on this input, we get either set of vafs on an nondeterministic fashion. 

Have you seen this phenomena before? We can transfer you the bam so that you can reproduce the problem.

**Comment by jsmedmar** [comment] 2018-06-25 14:14
On it, will update soon

**Comment by ElsaB** [comment] 2018-06-25 14:38
Hey, thank you for the update.

Gunes will ftp one of the problematic bam at Sanger, will tell you when done.

For that specific bam here are the indels that we vaf-corrected:
1	27088787	AG	A
11	32449576	CG	C
11	118307413	CGCG	C
16	18846453	TG	T
18	42530485	GA	G
19	33792731	G	GGCGGGT
2	25965302	T	TGGGGGGGGGGGGAGGGGGGGGGGGGGGGGGGGG
20	57429907	AC	A
22	30735119	CT	C
22	41550998	G	GT
4	106155778	GA	G
6	15487733	AC	A
7	101892149	G	GC
7	148543685	CATACTCT	CAAAAAA
7	148543687	TACTCT	TAAAA
9	139395259	G	GC
9	139396918	CG	C
X	123184968	TA	T
X	123195616	TTTA	T

and for instance the insertion on chr19 did oscillate between VAF 0 and 1.

Thank you

**Comment by ElsaB** [comment] 2018-06-25 20:48
Hello,

apparently there used to be a directory called _cgpdata7_ where Gunes/Elli could FTP and copy data, but it seems that the folder no longer exists.

Do you know where they could have write access so that we can copy over the BAM file?

**Comment by drjsanger** [comment] 2018-06-26 10:21
@ElsaB we can set up a Globus endpoint for you?

**Comment by ElsaB** [comment] 2018-06-26 14:30
Yes sure, let's do Globus.

I am not familiar with that system, happy to receive instructions.

**Comment by drjsanger** [comment] 2018-06-28 08:03
@ElsaB @jsmedmar can you confirm which version of vcfCorrect you're using please?

**Comment by sb43** [comment] 2018-07-10 15:45
Thanks @drjsanger for meticulous efforts and finding the root cause.
I agree to the proposed solution as quick fix however would inclined towards use of .bas file to get read_length and library_size information as suggested by @keiranmraine in issue [46](https://github.com/cancerit/vafCorrect/issues/46) and [47](https://github.com/cancerit/vafCorrect/issues/47l)
and completely remove the use of bam file for this purpose.

**Comment by drjsanger** [comment] 2018-07-10 15:49
@sb43 I agree. However these changes would be a hotfix whereas removing support for running vafCorrect without a `.bas` file (change of functionality) would be feature release.

**Comment by keiranmraine** [comment] 2018-07-10 20:40
@drjsanger Also ensure that the usual set of known bad reads are excluded.  I think we saw this problem in another tool estimating read-length that was written prior to use of BWA-mem and so didn't take into account supplementary reads being clipped.  I can't see any read filtering at all in the second snippet.

**Comment by keiranmraine** [comment] 2018-07-10 20:57
FYI, for calculating insert-size you should technically only consider r1 of a properly-paired pair (not secondard, supp, dup, qcfail), so a slight extra to the usual filters.

**Comment by drjsanger** [comment] 2018-07-11 17:55
@keiranmraine As far as I delved into the code there was no filtering for the read length calculation. 
I'm thinking we should make the filtering of reads a command-line option with standard filter as the default to allow for other use cases.

**Comment by drjsanger** [comment] 2018-07-13 10:08
This is corrected in [5.3.9](https://github.com/cancerit/vafCorrect/releases/tag/5.3.9)
Thank you for your help in providing data to assist in fixing this @jsmedmar @ElsaB

**Comment by jsmedmar** [comment] 2018-07-13 18:35
amazing David, did usage change? Or just a matter of bumping up the version?

**Comment by drjsanger** [comment] 2018-07-13 18:41
No usage change, but the filters added to the Bio::DB::HTS->features call to fetch reads for read length can be changed via additional options if required. As per samtools the are `-f` and `-F` at commandline. Defaults can be found in [`VafConstants.pm`](https://github.com/cancerit/vafCorrect/blob/dev/perl/lib/Sanger/CGP/Vaf/VafConstants.pm) 
https://github.com/cancerit/vafCorrect/blob/344690c8f41770defd206b1d40963d9bf3364a11/perl/lib/Sanger/CGP/Vaf/VafConstants.pm#L45-L55

**Comment by jsmedmar** [comment] 2018-08-21 20:33
Hey @drjsanger, got this error when trying to run on [my test / fake data](https://github.com/leukgen/click_pileup/tree/master/tests/data), is it possible my reads were filtered out or something?

```
Use of uninitialized value $read_len in multiplication (*) at /opt/bundle/lib/perl5/Sanger/CGP/Vaf/Data/ReadVcf.pm line 843.
```

**Comment by jsmedmar** [comment] 2018-08-21 21:02
You can replicate by running:

```
git clone https://github.com/leukgen/click_pileup
cd click_pileup/tests/data

ln snv.bam dummy_normal.bam
ln snv.bam.bai dummy_normal.bam.bai

cgpVaf.pl \
    --bed_only 1 \
    --bedIntervals ./indels.bed \
     --variant_type indel \
    --inputDir . \
    --genome ./reference.fasta \
    --normal_name dummy_normal \
    --outDir . \
    --restrict_flag 0 \
    --tumour_name snv ind
```

**Comment by sb43** [comment] 2018-10-24 09:06
resolved in last release

**Closed by sb43** 2018-10-24 09:06 UTC

**Comment by jsmedmar** [comment] 2019-03-11 21:26
hey @sb43 what are you referring to as resolved? is it the issue described in here https://github.com/cancerit/vafCorrect/issues/45#issuecomment-414820690?

**Comment by drjsanger** [comment] 2019-03-12 09:41
Testing with the above files @jsmedmar provided, using the default include and exclude filters lets only 2606 reads through to the read length check. 

Given `$Sanger::CGP::Vaf::VafConstants::NO_READS_READLEN` currently == 50000
https://github.com/cancerit/vafCorrect/blob/86ac7976c3e051a3cbbe503e876ed42f76c66d8e/perl/lib/Sanger/CGP/Vaf/VafConstants.pm#L45 

See below function for context of use of the above constant. I think there should be an additional return of `$mapped_length` if there were at least some reads. And perhaps throw an exception if no reads found in order to make this part more robust. Pretty sure that explains why @jsmedmar is getting his error listed above.

https://github.com/cancerit/vafCorrect/blob/db5933889e75aaeb0a57d43a40ce3bf4c6c768aa/perl/lib/Sanger/CGP/Vaf/Data/ReadVcf.pm#L891-L909

**Comment by jsmedmar** [comment] 2019-03-12 15:08
Thats ok, my test data is very small anyways so probably that won't happen in real life. Will see If I can update my tests. Thanks David

**Comment by jsmedmar** [comment] 2019-03-12 15:18
It would be nice though to create some test data and add it to this repo. This is how I did it for mine previously:

1. Two samples were identified, one with a SNP and another with an Indel:

    | Sample               | Chromosome | Position | Reference | Alternative               |
    | -------------------- | ---------- | -------- | --------- | ------------------------- |
    | I-H-113387-T1-1-D1-1 | 19         | 33792381 | C         | CCTTCTGCTGCGTCTCCACGTTGCG |
    | I-H-112855-T1-1-D1-1 | 22         | 41545846 | C         | T                         |

1. The bamfiles were subsampled with:

        IND_REGION='19:33790000-33800000'
        SNP_REGION='22:41540000-41550000'
        samtools view -b I-H-113387-T1-1-D1-1.bam $IND_REGION > ind_src.bam
        samtools view -b I-H-112855-T1-1-D1-1.bam $SNP_REGION > snv_src.bam

1. Then a small reference was created:

        GENOME=/ifs/work/leukgen/ref/homo_sapiens/GRCh37d5/genome/gr37.fasta
        samtools faidx $GENOME $IND_REGION > reference.fasta
        samtools faidx $GENOME $SNP_REGION >> reference.fasta

        # rename chromosomes
        sed -i "s/>$IND_REGION/>19/" reference.fasta
        sed -i "s/>$SNP_REGION/>22/" reference.fasta

        # index reference
        samtools faidx reference.fasta
        bwa index reference.fasta

1. Small bams aligned to small reference:

        bwa_mem.pl -o . -reference reference.fasta -s ind ind_src.bam
        bwa_mem.pl -o . -reference reference.fasta -s snv snv_src.bam

1. Now the new SNP and Indel postions are:

        INDEL_POS = 33792081 - 33790000 + 1 = 2382
        SNP_POS   = 41545546 - 41540000 + 1 = 5847

    So the final test data:

    | Sample | Chromosome | Position | Reference | Alternative               | Expected VAF |
    | ------ | ---------- | -------- | --------- | ------------------------- | ------------ |
    | indel  | 19         | 2382     | C         | CCTTCTGCTGCGTCTCCACGTTGCG | 0.43         |
    | snv    | 22         | 5847     | C         | T                         | 0.34         |

**Comment by jsmedmar** [comment] 2019-03-12 16:38
Just to check, I tried bypassing the XX if statement:

Yet found another error:

```
Illegal modulus zero at /opt/bundle/lib/perl5/Sanger/CGP/Vaf/Process/Variant.pm line 492.
```

https://github.com/cancerit/vafCorrect/blob/db5933889e75aaeb0a57d43a40ce3bf4c6c768aa/perl/lib/Sanger/CGP/Vaf/Process/Variant.pm#L492

I think this one has nothing to do with the size of my test bams...

**Comment by jsmedmar** [comment] 2019-03-12 20:06
Also want to confirm that `cgpVaf.pl 5.4.0` does work on the real bams (not the subsampled ones)

**Comment by sb43** [comment] 2019-03-13 10:08
> hey @sb43 what are you referring to as resolved? is it the issue described in here [#45 (comment)](https://github.com/cancerit/vafCorrect/issues/45#issuecomment-414820690)?

@jsmedmar  The issue with non-deterministic results is now resolved.
Also there is preference to use  .bas file to get read length information over .bam file
http://www.internationalgenome.org/category/bas/

**Comment by keiranmraine** [comment] 2019-03-13 13:21
Please note that the BAS files used in our tools are a derivative of that format.

**Comment by sb43** [comment] 2019-03-13 14:08
Yes @keiranmraine is right,  if required user can modify the custom column names in VafConstants file to set following parameters which are used for library size calculations.
Sanger::CGP::Vaf::VafConstants::LIB_MEAN_INS_SIZE 
Sanger::CGP::Vaf::VafConstants::LIB_SD

**Comment by jsmedmar** [comment] 2019-03-13 15:52
Ok cool! I fixed my test data by increasing the total number of reads in each bam. Also the error `Illegal modulus zero at /opt/bundle/lib/perl5/Sanger/CGP/Vaf/Process/Variant.pm line 492.` was caused because the test bams didn't have reads in some regions, fixed with:

```diff
IND_REGION='19:33790000-33800000'
SNP_REGION='22:41540000-41550000'

# create test bam for indels
-samtools view -b I-H-113387-T1-1-D1-1.bam $IND_REGION > ind_src.bam
+samtools view -b I-H-113387-T1-1-D1-1.bam $IND_REGION $SNP_REGION > ind_src.bam

# create test bam for snvs
-samtools view -b I-H-112855-T1-1-D1-1.bam $SNP_REGION > snv_src.bam
+samtools view -b I-H-112855-T1-1-D1-1.bam $IND_REGION $SNP_REGION > snv_src.bam
```

**Comment by jsmedmar** [comment] 2019-03-13 16:03
Ok cool! I fixed my test data by increasing the total number of reads in each bam. Also the error `Illegal modulus zero at /opt/bundle/lib/perl5/Sanger/CGP/Vaf/Process/Variant.pm line 492.` was caused because I included an `snp` in the bed file whilst running in `indel` mode. Truly appreciate your help
